### ISSUE TITLE
Drop-down menus don't display on an iPad (retina) in landscape mode 

### ISSUE THREAD

**Issue by motionbureau** [Obox/layerswp#10]
## Description of issue
On an iPad Retina with iOS 8 in landscape mode, this theme goes in to desktop mode & drop-down menus don't work.
In portrait mode, theme goes to Mobile mode & it works correctly.

- Doesn't happen on an iPhone with Retina screen.
- Doesn't happen on an iPad 1(1024x768). Renders desktop mode in landscape & drop-down menus work correctly .

## Web Browser(s) that exhibit the issue
Safari iOS 8 with iPad with Wordpress 4.1.1 and layerswp 1.0.2
iPad 4 Retina(2048x1536)

**Comment by vailjoy** [comment]
Hello!

Thank you for your feedback :)

This is indeed a tricky one - with responsive CSS alone, we can't account for the fact that tablets won't let you hover, and because this is a desktop resolution we can't force a mobile menu here either. (You can do that on your site with custom css if you prefer). We will need to take a look at the most elegant solution for allowing tap activation on drop-downs when viewing from a mobile browser. Thanks again!

**Comment by motionbureau** [comment]
If I didn't want to display the horizontal menu & its drop-downs & only display the responsive menu with CSS, how would I load the responsive menu on the ipad Retina models(landscape) if I was using this @media check(which works):

thanks

```
@media only screen 
and (min-device-width : 768px) 
and (max-device-width : 1024px) 
and (orientation : landscape)
and (-webkit-min-device-pixel-ratio: 2) { 

  /* CSS to hide horizontal nav & display responsive nav  */

}
```
