### ISSUE TITLE
Reinstalling theme, custom styles made before, not removed.

### ISSUE THREAD

**Issue by RomkaLTU** [Obox/layerswp#133]
First time installed this amazing builder and after playing around decided to build some little landing page of course i didn't created child theme when tested first time, so i uninstalled theme, removed created content, and when tried to install again styles was same as before (Site settings: colors), not defaults. I'm talking about CSS styles (header background). How to reset default state of theme without re-installing WP? Also i think it should be ok to remove created content when deleting theme completely.

**Comment by vailjoy** [comment]
Hi there,

This is because settings are not stored in a file, but in your database and linked to the active theme id. It is actually a good thing that those settings are not lost between reinstalls! We do not ever want to purge customizations on a reinstall, since this is effectively what happens when themes get updated.

If you are trying to do a "fresh" install, you must also purge your database tables. You may be able to find a plugin that purges JUST the theme  tables. If you just want to get rid of custom css, go into the Customizer and ensure the CSS panel is blank.
