### ISSUE TITLE
Where is the content and layout position stored?

### ISSUE THREAD

**Issue by creativeer** [Obox/layerswp#168]

**Comment by creativeer** [comment]
Have upgraded to Version 1.1.5 and was working on a Site with nearly 37 pages. After the Upgrade all the Content and Widget Positions are lost. Have tried to reinstall Layers and my Child Theme, but no Chance. If i export a .json file from one of these pages, its just "null" in there. Yes i forgot to Export these pages before, my fault. But one Question for me is: Is there no other place where you can store the content of the layout builder? If i look in the sql database, all title of these pages there and the metadata for attachments, menu title, its all there, but not the important content..

**Comment by marcperel** [comment]
Hey there,

That's terrible, we are working on methods to backup sidebars and widgets so that you can roll back to the last stable version, even if the process is manual, but for now...

The widget settings are stored in the `wp_options` table, the `open_name` is `sitebars_widgets`.

Have a look there, the option could still have data. Otherwise look for `theme_mods_{child-theme-slug}` and see if `sidebars_widgets` is saved in a serialized array in that option, you may be able to salvage your widget settings form that option.

I'd suggest first exporting your database as a back before attempting any of these changes though.

**Comment by creativeer** [comment]
Maybe it has to do with numbers of pages, but i have on some pages the content of widgets from other pages. widgets that was saved, aren't there anymore. with how many pages have you made a stress test?

**Comment by marcperel** [comment]
It's certainly a worthwhile test, we'll run it as soon as possible.

We do know that if you're in the customizer and you exit half way through
the Save & Publish action, there are some issues that arise with regards to
widget settings, although that's an issue WordPress is helping fix with
*4.3*

**Comment by creativeer** [comment]
Ok, sounds good.
Thx for your effort Marc.

**Comment by newlocalmedia** [comment]
I'm finding that making any changes to the options table ends up wiping out all content in the content widget. See #207.

**Comment by vailjoy** [comment]
This has been resolved from Layers end with revisions in 1.2.11
