### ISSUE TITLE
Can't add custom control to 'title_tagline'

### ISSUE THREAD

**Issue by meydjer** [Obox/layerswp#173]
First, congratulations for this awesome work.

I can't add a custom control to "title_tagline" section. If I change to any other existing section it works perfectly.

Here is my snippet:

```
add_filter( 'layers_customizer_controls', 'my_customizer_controls');
 
function my_customizer_controls( $controls ){

	$controls['title_tagline'] = array(
		'display-tagline' => array(
			'type'  => 'layers-checkbox',
			'label' => 'Display Tagline',
			'default' => 0
			)
		);

    return $controls;
}
```

I'm missing something?

**Comment by naumanahmed19** [comment]
Following code from docs and working fine. 

```
add_filter( 'layers_customizer_controls', 'my_layers_customizer_controls' );

function my_layers_customizer_controls( $controls ){

    $social_media_controls = array(
       'social-twitter' => array(
            'type'      => 'layers-text',
            'label'     => __( 'Twitter Username' , 'layerswp' ),
        )
      

    $controls['header-layout'] = array_merge( $controls['header-layout'], $social_media_controls );

    return $controls;
}
``

**Comment by NGorco** [comment]
the same issue. No decisions for now((

**Comment by marcperel** [comment]
Yeah, I'm afraid that for the title_tagline you'll have to use traditional Section / Control editing. Why? Because that section is not a specific Layers section, it is added by Jetpack, or at least a fork of Jetpack inside Layers.

Thanks for bringing it up though it's actually something we had an issue with ourselves last week before realizing it's the one section that still requires the traditional WP method.

**Comment by meydjer** [comment]
I understand. It would be great to see this information inside docs.

Thank you, @marcperel.
