### ISSUE TITLE
Archives post list class?

### ISSUE THREAD

**Issue by ckubs** [Obox/layerswp#23]
Noticed something strange on taxonomy pages( let's say a category archive). The section with articles acquires as CSS classes the classes of the first article, for example if the first post is the one with id 35628, it goes :
 `<section class="post-35628 post type-post status-publish format-standard has-post-thumbnail hentry category-tehnica ...etc">` and the articles in the list, including the first one have only `<article class="push-bottom-large">`

This is how it works for now, I could have a compatibility issue with the plugins I use or it could be a framework bug?

**Comment by vailjoy** [comment]
Hi there,
It looks like we are using the <?php post_class();?> hook to let WordPress assign the post classes for the main post container, which wraps the loop whether it is a post list or a single post. This assigns a unique ID for that section which is not the id of the first post. This should not conflict in any way with plugins you have installed, it is just there as a way to ensure the post column gets consistent styling and can be targeted easily for custom styling in kits and themes. If you click the link to view the single post, you will notice this same set of post classes gets assigned to the section wrapper, but has the ID of that specific post.  Here is the codex info for reference:

http://codex.wordpress.org/Function_Reference/post_class

**Comment by ckubs** [comment]
@vailjoy That ID( 35628) aquired by thes ection is the Id of my first article in the section. I thought that classes should be acquired by the article they belong to, not by the whole section as it happens now, when the whole section acquires the first article post_class(), and the actual posts don't have any specific classes.

**Comment by vailjoy** [comment]
Hello,

post_class can be used in or outside of the loop and is purely there for theming purposes to give you finer control over targeting a specific element. In the case of the archives/blog, we apply it to the section to keep that section consistent theme-wide. We do not apply it to the article container, because that 
1. applies the container class, which keeps the layouts from working correctly (container needs to be on the column, not the articles in the feeds)
2. it applies the post class, which carres styling for the post container, whether it contains a feed or a single post's content.

post_class generates a class name only not an ID. The class name has no actual relation to the post or posts themselves. It is purely aunique CSS selector.

You could, theoretically, apply post_class to the <article> in addition to the section, but this will duplicate the *class* of the first post in category archives that don't have their own IDs, as you have pointed out. That should not actually affect anything since nothing should be using the unique selector other than you in custom css (the two being separated easily by virtue of position in the cascade). If you are finding a plugin that is trying to the Wp generated post class  to locate posts or similar, the plugin author needs to change their method to be looking for the actual ID selector, not a class name. Ie id="post-<?php the_ID(); ?>" vs post_class(); or they should be injecting their own class via filtering post_class.

I will discuss this with the team regargin whether they feel there is any value in using post_class in the content-list loop, but for now it will not be removed from the sections unless we see evidence of an actual bug resulting from it being there.

**Comment by ckubs** [comment]
Oh, ok, I think I understand now. So you made the section to get the first article post_class, and the articles in the category to have only push-bottom-large. It's not a bug.
