### ISSUE TITLE
Sticky header no transparent even if option is flagged

### ISSUE THREAD

**Issue by webmas** [Obox/layerswp#252]
I have noted this issue in last days in a running and in develop site.
Made today a new installation with latest Wordpress 4.3, Layers 1.2.4.2 but when apply sticky header and transparent option, in customizer, the transparent class applyed is overwritten by some inline style in the page displayed with the transparency set to 1.
Tryed with cache plugin and without it, the problem persist.
Am I in wrong?
It seems the option selected in customizer are not applyed to code.

![home-page](https://cloud.githubusercontent.com/assets/6018116/9584593/49d23326-5012-11e5-851b-cf3ed3c463a9.jpg)
![customizer1](https://cloud.githubusercontent.com/assets/6018116/9584594/49d85b2a-5012-11e5-82c2-03efafa7727a.jpg)

**Comment by webmas** [comment]
Found the code with the possible bug :
in file /core/helpers/template.php lines 409-410 remove comment slashs 
From 
  		//$bg_opacity = ( layers_get_theme_mod( 'header-overlay') ) ? .5 : 1 ;
		$bg_opacity = 1;
To 
		$bg_opacity = ( layers_get_theme_mod( 'header-overlay') ) ? .5 : 1 ;

**Comment by davidperel** [comment]
Hi @webmas 

The transparent overlay issue that you're experiencing is intentional. It will be transparent on pages where there is a .title-container or slider widget in the body. Otherwise it applies a background color so that you can still read the menu items and see the logo.

The is especially relevant on sites which have white backgrounds.

If you want to override it on scroll then you can apply css to the following class:

.header-sticky.is_stuck.is_stuck_show{}

Dave
