### ISSUE TITLE
Trouble with RTE code view in content widget

### ISSUE THREAD

**Issue by ajbat21** [Obox/layerswp#253]
love what you guys were trying to create... i have been using layers since I found it on product hunt. But it seems like the more updates... the more unstable Layers becomes... 

Here are the issues that I am experiencing:
- When using code in (HTML editor) content module after pasting code... cannot edit code.
- In content module... editor function buttons sometime disappear. 
- Page editor drop down... no longer available.
- Adding image to footer. No longer available

Using latest version. but everytime i get use to one set of features seems link everything changes. not sure what to do.

**Comment by vailjoy** [comment]
Hi there,

#1: if you click the Code view button and then write in some HTML ie ```<div class="myclass">text</div>``` or use the RTE toolbar to add something like a list, can you switch to code view and edit it? (add a class to the ul for example). This will help determine if the issue is with the code you are pasting (be sure you are using Ctrl\Cmd+Shift+V)
#2 This is normal, they should reappear when you click back into the field (there may be a delay depending on how slow your customizer is working)
#3 Can you provide more detail re: Page Editor Drop-down (where are you looking?)

I can confirm images can be added to the footer text area if you use full urls and the correct HTML.
http://docs.layerswp.com/doc/how-to-add-images-to-the-footer/

Please ensure you are on Layers 1.2.4, have deactivated all plugins to retest, and have updated WordPress.

**Comment by vailjoy** [comment]
https://github.com/Obox/layerswp/issues/228
