### ISSUE TITLE
2nd order dropdown menu hidden on small screens

### ISSUE THREAD

**Issue by DieTapete** [Obox/layerswp#264]
Dropdown 2nd order menus always open to the right. This becomes an issue if the window is smaller and hides the window.
![img_2015-09-16 22 15 20](https://cloud.githubusercontent.com/assets/1159445/9917179/7b34888c-5cc0-11e5-85cc-3a87d28803be.jpg)
Possbile Solution: Menus should open to the left when the screen is too small.

**Comment by vailjoy** [comment]
Hi there,
We have the menu orientation reversed on the last child only - the sub-child being cut off of any other menu link otherwise depends totally on the width of its parent and the last child so we can't really force them all to pop out to the left. To resolve this on your setup you can reset your tertiaty menu position like this:

.nav > ul > li .sub-menu .sub-menu {
    left: initial;
    right: 185px;
}
