### ISSUE TITLE
Bug - Latest Posts - Overlay

### ISSUE THREAD

**Issue by VadymVolos** [Obox/layerswp#292]
Bug - Latest Posts - Overlay
![2015-11-18_13-04-24](https://cloud.githubusercontent.com/assets/12669290/11239487/f9f2851a-8df4-11e5-8383-4657dfe3818e.gif)

**Comment by VadymVolos** [comment]
Working! But no buttons and a title:
![2](https://cloud.githubusercontent.com/assets/12669290/11240230/b6d70d96-8df9-11e5-88b3-c253598a413c.png)

**Comment by marcperel** [comment]
They should appear if you hover over the image

**Comment by VadymVolos** [comment]
I know. On the big screen - appear. If browser is narrow - no appears.

**Comment by vailjoy** [comment]
Hi there,
Try testing using responsinator.com rather than manually resizing the browser and please let us know which widths there is a problem if possible, thanks!

**Comment by VadymVolos** [comment]
responsinator.com:

![112](https://cloud.githubusercontent.com/assets/12669290/11590598/fb50c1d6-9a99-11e5-8429-7425a8acf971.jpg)
![111](https://cloud.githubusercontent.com/assets/12669290/11590599/fb6f5a42-9a99-11e5-9dba-5b9a9d490037.jpg)

**Comment by vailjoy** [comment]
Hi there,

OK this is actually working as designed as far as the overlay being removed on mobiles (which is not related to any image ratio issues) When you go down to tablet or smaller, the overlay is removed and converted to normal post layout as there is no hover functionality on a touch screen device. Make sure you also account for these views when customizing styles (the DevKit plugin is a huge help for this since it has built-in tablet and mobile view tabs in the customizer.) The following tutorial goes through how to customize responsive views using either DevKit or your own media queries in CSS. 

http://docs.layerswp.com/doc/how-to-customize-the-mobile-or-responsive-views/
