### ISSUE TITLE
Posts YouTube video: ERR_FAILED fjhoaacokmgbjemoflkofnenfaiekifl/cast_sender.js

### ISSUE THREAD

**Issue by VadymVolos** [Obox/layerswp#305]
Failed to load resource: net::ERR_FAILED fjhoaacokmgbjemoflkofnenfaiekifl/cast_sender.js

To stop seeing those cast_sender.js errors, edit the youtube link in the iframe src and change embed to v

http://stackoverflow.com/questions/25814914/chrome-youtube-cast-sender-js-console-error
https://code.google.com/p/google-cast-sdk/issues/detail?id=309

**Comment by vailjoy** [comment]
Hi there,
Please continue with the orginal issue here:
https://github.com/Obox/layerswp/issues/294

I am unable to recreate this issue. For YouTube, make sure you are using the YouTube Share URL and have tested with all plugins disabled.

Since we use oembed and not iframe embeds, the only way you can control this is to use the iframe embed in the Text tab of your post.
