### ISSUE TITLE
the_content filter issue

### ISSUE THREAD

**Issue by gthapar** [Obox/layerswp#317]
Hello,

I am trying to add share buttons after content on every post using the 'the_content' filter. But when I do this the buttons also appears after slider content. How can this be fixed?

**Update**
There is an option to select where the buttons should be displayed. It can be post, page or any custom post type or all of them together.

Best Regards,
Gautam Thapar

**Comment by StuartOB** [comment]
Perhaps think about using a conditional to make sure that your filter is only run in your specified post_type. see this example to have your filter only work for posts
```
if ( 'post' == get_post_type() ) { ... }
```

**Comment by gthapar** [comment]
Yes, that's fine but if I use `if( is_singular( 'page' ) ) { ... }` but still it displays my buttons in the slider.

**Comment by StuartOB** [comment]
perhaps if you sent a screenshot of what is going wrong. So I can better see where the buttons are/aren't showing?

**Comment by gthapar** [comment]
Sure, I have attached a screenshot. See the Facebook button appears after the content.
![layers-slider](https://cloud.githubusercontent.com/assets/4481867/12376397/2e6352b4-bd18-11e5-9bf8-3d72efee5655.png)

**Comment by gthapar** [comment]
Best would be that you just add the below code maybe in layers theme itself or using a plugin and check the slider..
```php
 add_filter( 'the_content', 'test_layers_slider' ); 
 function test_layers_slider( $content ) { 
    if ( is_singular('page') ) {
        $content = $content . ' My custom content ';
    }
    return $content;
}
```

**Comment by vailjoy** [comment]
1. I recommend fixing this with CSS, since you cannot tell the function to skip a widget in particular without supporting javascript (overcomplicated).  Example:

.swiper-slide .yoursharebutton{display: none;}

2. To keep the buttons from outputting in any layers page/widgets content, the correct condition is:

`if( is_page() && wp_basename(get_page_template()) == 'builder.php') ) { ... }`

I recommend using a child theme for any custom functions otherwise you will need to re-edit layers everytime there is an update.
