### ISSUE TITLE
Dropdow submenus in all the menus, not main menu only

### ISSUE THREAD

**Issue by ckubs** [Obox/layerswp#319]
I'm triyng to make something good with Layers. 

Despite the problem with Buddypress that isn't working( I posted the problem in the Layers forum and hope someday I'll get it fixed) I see that only Layers main menu works with dropdowns. 

The other menus don't. I need a dropdown in the top menu, or in a third menu, added with hooks after the logo and the dropdown's arrow is there, the content of it is there but the submenu is blocked from opening.

**Comment by vailjoy** [comment]
Hi there,

The top menu won't render a drop-down, because it covers content in the header (bad ux). Menus you add with a hook would have their level set by you to determine whether they support drop downs or not, and then require the supporting CSS by you. All of these are child theme customizations that you would need to resolve and are not issues with the Layers core. Hope that makes sense. Please use the community forum for help with CSS or solving styling issues like blocked dropdowns (if the drop is there, usually it is just an overflow issue)
