### ISSUE TITLE
Can't edit LayersWP Pages

### ISSUE THREAD

**Issue by EpicnessTwo** [Obox/layerswp#323]
Every time I go to edit a page on my LayerWP website, it brings up the default editor for the homepage. I can't edit page content anymore and it's randomly happened. No config changes have been made or any new installs of plugins or removals. I'm not sure how long this has been there since it's been a little whilst since I edited anything on my website.

**Comment by EpicnessTwo** [comment]
Might be worth noting. I get this error in the inspector which could be related.

customizer-preview.js?ver=2e1c866791077dc2a559ca85e2c56220:1 Uncaught TypeError: Cannot read property 'bind' of undefined

**Comment by vailjoy** [comment]
Hi there,
For faster help with troubleshooting technical issues, please go to Layers > Dashboard and enable the Layers Messenger to shoot us a support request.

To troubleshoot your customizer, 

1. Ensure you have updated to Layers Updater 1.3 and Layers 1.2.10
2. Run any other updates prompted under Dashboard > Updates
3. Clear your browser cache and try again. Also test creating and editing a new page to ensure it is not being caused by content in that specific page.
4.If issues persist, deactivate your plugins, then clear your browser cache and try again. If that solves it, you have a plugin conflict. If issues persist,please go through the following:
http://docs.layerswp.com/doc/troubleshooting-customizer-errors/

**Comment by EpicnessTwo** [comment]
Hi, I've disabled all but one plugin now as that plugin is required to keep my site accessible (Cloudflare Flexable SSL). The problem is still here. I have updated layerswp today and the updater (Now disabled is on the latest update). I will link some screenshots of interest below.

https://i.epickitty.uk/lTV0Tk
https://i.epickitty.uk/dgFrqP
https://i.epickitty.uk/DQO4u7
https://i.epickitty.uk/A4taBz
https://i.epickitty.uk/BAz95b

**Comment by vailjoy** [comment]
Hi there,
Sorry for the late reply - for help and support of Layers it is really best to use Layers Messenger, which you can enable under Layers > Dashboard. We do not monitor GitHub for support requests.

Please try the following troubleshooting, then hit us up on the messenger if issues persist. This could very well have to do with Cloudflare SSL if it is modifying your URLs in any way.
http://docs.layerswp.com/doc/edit-layout-panel-never-appears-in-customizer/
