### ISSUE TITLE
Enable shortcodes in Customizer's text input fields

### ISSUE THREAD

**Issue by lamosty** [Obox/layerswp#39]
I've began to customize my site through Customizer and wanted to output dynamic year in the copyright section in the footer. It would be nice if I could use a shortcode to display year dynamically, for example. Not something important but other users might find it useful too. What do you think?

![](http://i.imgur.com/7zdmAEw.png)

**Comment by vailjoy** [comment]
Hi there,
This is not possible due to how the text sanitization need to work. If you need to add shortcode output to a location in layers and cannot do it with a widget, it is best to use a child theme and any one of the layers hooks to inject <?php do_shortcode('[working-shortcode]'); ?>. 

http://docs.layerswp.com/theming/
http://docs.layerswp.com/using-actions-filters-hooks/
http://docs.layerswp.com/reference/layers_after_footer_copyright/
