### ISSUE TITLE
Whitelabelling?

### ISSUE THREAD

**Issue by swhinnem** [Obox/layerswp#64]
Your site mentions that it's possible to whitelabel Layers for client sites but I couldn't seem to find any documentation about it. Can you point me or let me know how it works?

**Comment by vailjoy** [comment]
Hi there,
Please use our help site for general questions (Help and Documentation > Ask Question). You may also find a Child Theme guide under For Developers which provides advice for modifying the front-end of Layers:
http://docs.layerswp.com/

You can turn off the Layers icon link in the footer under Layers > Customize in the Footer layout options.

The Layers framework itself cannot be white-labelled perse. If you just want to hide Layers options in the Admin from your client, you can use a plugin such as Members by Justin Tadlock and Admin Menu Editor

**Comment by swhinnem** [comment]
Thanks for the response. I did look thoroughly through the documentation and didn't find anything about it. On the [developers page](http://www.layerswp.com/developers/), it specifically says 'White label Layers when using it on client projects'. Is this not true?

**Comment by vailjoy** [comment]
He is referring to turning off the layers badge on the front-end. To hide the Layers menu from the admin, you need to use the menu editor plugin (or there are some other nice ones like Whitelabel CMS that can do this). You cannot remove the Layers branding from the product such as on our widgets and so on, or remove the license or attribution info. If you want to fork the product and extend it into your own theme, you are free to do so :)

**Comment by swhinnem** [comment]
OK, if that's the case, then you should not market it as whitelabel-able. It's a little misleading. I understand this is a free and open source product, but just be honest.

**Comment by marcperel** [comment]
A note on this Sarah @swhinnem,

It is possible to whitelabel Layers using the Code Style localization plugin, since all mentions of Layers are translatable:

http://www.code-styling.de/english/development/wordpress-plugin-codestyling-localization-en

It's certainly the safest way to completely whitelabel Layers and make sure that any mention of Layers is completely hidden. If the option to change the Layers mentions was simply an option in the admin panel it would be visible by your clients.

 ~ Marc
