### ISSUE TITLE
Empty ..json file during export

### ISSUE THREAD

**Issue by ajbat21** [Obox/layerswp#70]
When exporting a layout my .json file downloaded as an empty file. I am pretty sure that it is a plugin conflict of some sort. When I disabled all my plugins all worked fine. I am not sure which plugin as I did not have time to disable one-by-one. 

Here is a list of the plugins that I have installed.
Layers - Updater
Menu Icons
NextGEN Gallery by Photocrati
OutstandingBar
PHP Code Widget
Shortcodes Ultimate
Simple Custom CSS
Visual Form Builder Pro
Visual Form Builder Pro - Form Designer
WP Super Cache

**Comment by vailjoy** [comment]
Hi there,

You would need to do the one by one test to know for sure. I can only tell you Shortcodes Ultimate, menu icons and the Updater have been tested in Layers before and shouldn't be an issue. The custom css plugin is not needed since Layers already provides that functionality. PErhaps try with WP Super Cache off first.

**Comment by vailjoy** [comment]
Hi there, just checking in -
Are you still having this issue with your setup and the current layers version?

**Comment by ajbat21** [comment]
Everything seems to be working fine.
