### ISSUE TITLE
Error trying to create new page of type "Application"

### ISSUE THREAD

**Issue by coolxeo** [Obox/layerswp#75]
Debug information:
I can't add anymore Content Widgets. If I click on add widget of "Content" type. The call to the server is made and is cancelled, this is the information sent
```
wp_customize:on
theme:layerswp
customized:{"widget_layers-widget-column[3]":{}}
nonce:98dee5b597
customize_messenger_channel:preview-1
```

Debugging more, I tried to create a new page, the ajax call is made but doesn't continue. This are the errors generated in apache log. The page is created but only slide component is added. My guess is it fails when try to create "Content" type widget
```
[Thu Apr 23 16:28:59] [:error] [pid:tid] [client ] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Warning:  Invalid argument supplied for foreach() in /var/www/wp-content/themes/layerswp/core/helpers/migrator.php on line 732, referer: /wp-admin/admin.php?page=layers-add-new-page
Thu Apr 23 16:28:59] [:error] [pid:tid] [client ] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Fatal error:  [] operator not supported for strings in /var/www/wp-content/themes/layerswp/core/helpers/migrator.php on line 755, referer: /wp-admin/admin.php?page=layers-add-new-page
```

**Comment by matteogamba** [comment]
screenshots of the problem.

![screenshot 2015-04-24 14 37 08](https://cloud.githubusercontent.com/assets/3117946/7319774/ded71a74-ea8f-11e4-9755-c2531da502f8.png)
![screenshot 2015-04-24 14 36 44](https://cloud.githubusercontent.com/assets/3117946/7319775/ded7ae9e-ea8f-11e4-8614-1de8f0ce59e1.png)
![screenshot 2015-04-24 14 37 20](https://cloud.githubusercontent.com/assets/3117946/7319776/dee0579c-ea8f-11e4-8684-0c89e2f138cf.png)

**Comment by vailjoy** [comment]
Hello!

As you can imagine this is very difficult for us to recreate. I was able to add 10 content widgets to a Layers page and customize them without issue on 1.1 though. You can check that out here:
http://vailjoy.com/layers/content-widget-test/

The extra Apply button gives me the impression that something else is conflicting with the customizer. Please try deactivating all plugins, then revisit the customizer in a new page and try again. If the issue is solved, reactivate your plugins one at a time and test in between until you find the one that causes this issue, If the issue persists with all plugins off, the next fastest thing to do is a full reinstall of Layers (activate the default theme in Appearance > Themes, delete Layers, reinstall with a fresh download of 1.1 - please be sure to do it over FTP and make sure the folder name is correct "layerswp" if you are using the github zip).

**Comment by coolxeo** [comment]
Thanks for answering @vailjoy we already try to reinstall and it doesn't work. We even try to uninstall and install again. I agree with you is it difficult to debug. We are going to try to reinstall wordpress completely

**Comment by marcperel** [comment]
Hey @Coolxeo,

Did you have any luck with a fresh WP install?
