### ISSUE TITLE
Q: add multiple widget in one row

### ISSUE THREAD

**Issue by Theme20** [Obox/layerswp#99]
Hello, 

I really like content builder but is there any way to add one "Row" as parent then add 3 widget 1/4 1/4 1/4 to it. My mean is one row with multiple widget like 1/3 = Search widget, 1/6 Carousel, 1/3 Info.

If you have worked with visual composer plugin before, it does one element named "Row" and user can add anything on it as child and also can change column size of each element. 

I think it would be perfect for layerswp and customers will increase.

Cheers

**Comment by omarabid** [comment]
@Theme20 I agree. I was surprised that there is no way to support multiple columns.

**Comment by marcperel** [comment]
Hi @Theme20 @omarabid,

Thanks for the feedback guys. Multiple widgets per row is a feature we played with months before launch, but because of the technical challenges as well as the mobile-first nature of Layers, found that one widget per row was how we'd launch.

It may be something we bring in at a later date, but we won't put a certain date or promise on it.

 ~ Marc
